In [2]:
import numpy as np

## Scalar

Numpy is the most important package for linear algebra, fast array - vector - operations and primitives.

Unlike vector or matrices, in Numpy there is no specific data type for scalars, rather we use the standard data types for integer and float in Python.

Object and name are separate. We just connect the name to the object.

In [1]:
a = 3.5
w = 10

## Vector

To create a vector we use the array() function. By his function you can create any n-dimenaional arrays, e.g. matrix and tensors. Numpy uses a row representation for vector, the opposite w.r.t. the notation we used, but it is only a matter of transposing.

In [6]:
w_vec = np.array([1, 2, 3, 4, 5.0]) # applying array function to a list
w_vec

array([1., 2., 3., 4., 5.])

Since at least one of the scalars in the vector is a float, the dtype of the vector is float64, i.e. each element of the vector is a float.

In [7]:
w_vec.dtype

dtype('float64')

An array is basically a list, so it supports most of the basic operations on list, e.g. indexing (selecting one element; each element has a position in the list, indexing starts from 0) and slicing (extension of indexing; we would like a sub vector of elements).

In [8]:
w_vec[1] # we are indexing the second element / second dimension of the vector w_vec

2.0

In [9]:
w_vec[1:3] # we're taking a subvector starting from index 1 and ending at index 2 (included)

array([2., 3.])

## Matrix

The function array() can also create matrices intended as a 2-dimensional arrays with nested brackets. To create an n x d matrix, we must stack n row d dimensional vectors.

Lists inside  a list

In [10]:
W = np.array([
    [1, 4, 7],
    [4.9, 4, 2]
]) # 2 x 3 matrix
W

array([[1. , 4. , 7. ],
       [4.9, 4. , 2. ]])

To select a specific row with index j, we use the standard indexing and slicing operations. The same holds for selecting columns.

In [11]:
W[0][:], W[0, :] # select row with index 0

(array([1., 4., 7.]), array([1., 4., 7.]))

In [13]:
W[0,1:] # select first row without first element

array([4., 7.])

In [14]:
# submatrix

W[:, 1:]

array([[4., 7.],
       [4., 2.]])

In [12]:
W[:, 1] # select column with index 1

array([4., 4.])

## Shape

The shape of an array returns the number of scalars for each dimension. You can access the shape of an array by the attribute shape.

In [15]:
W.shape, w_vec.shape

((2, 3), (5,))

## Transpose

The transpose of a vector or matrix can be obtained by the operator T.

In [16]:
W_T = W.T
W_T

array([[1. , 4.9],
       [4. , 4. ],
       [7. , 2. ]])

In [17]:
W.shape, W_T.shape

((2, 3), (3, 2))

## Operations on Vectors and Matrices

The corresponding operators in Numpy:

- Summing two vectors: x+y
- Vectors multiplied by a scalar: a * x
- Inner-product or dot-product: x.dot(y) or np.dot(x, y)
- Hadamard product of vectors: x * y

In [18]:
x_vec, y_vec = np.array([1, 2, 3, 4]), np.array([6, 7, 8, 9])

x_vec + y_vec

array([ 7,  9, 11, 13])

In [20]:
# vector and scalar sum

x_vec + 2

array([3, 4, 5, 6])

In [19]:
a * x_vec

array([ 3.5,  7. , 10.5, 14. ])

In [22]:
x_vec.dot(y_vec), np.dot(x_vec, y_vec)

(80, 80)

In [23]:
x_vec * y_vec

array([ 6, 14, 24, 36])

-> Must check dimensions when doing multiplication!

Here the corresponding poerator in numpy:
- Multiplying a matrix by a vector: M.dot(x) or M @ x
- Multipying two matrixes: np.dot(M1, M2) or M1 @ M2

In [24]:
A = np.array([
    [1, 0, 1],
    [0, 2, 1]
])

In [25]:
W @ np.array([2, 1, 1]) # shape of W is (2, 3) and the shape of vector is (3, 1)

array([13. , 15.8])

In [26]:
W.shape, A.shape

((2, 3), (2, 3))

In [27]:
W @ A.T

array([[ 8. , 15. ],
       [ 6.9, 10. ]])

In [28]:
W.T @ A

array([[1. , 9.8, 5.9],
       [4. , 8. , 8. ],
       [7. , 4. , 9. ]])

In [29]:
W @ A # error, because of dimensions

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## MAX, ARGMAX, ASSIGNMENT

In Numpy there is no straightforward function to compute the maximum of a function f(a), but we may exploit list comprehensions.

In [30]:
S = [2, 3.0, 0.5, 6, 1, -10]

def f(a):
    return a**2

np.max([f(a) for a in S])

100.0

In [31]:
S[np.argmax([f(a) for a in S])]

-10